import { GalleryItem } from './types';

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: 'grid_view' },
  { id: 'people', label: 'People', icon: 'group' },
  { id: 'selfies', label: 'Selfies', icon: 'face' },
  { id: 'nature', label: 'Nature', icon: 'nature_people' },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  // November group
  {
    id: 'img-1',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZanOqSCaNKVYBud2coSJo2-wNR0noBa4C5o7IYKgJcDhW9IgnAv9o2eL3bYbdr28JiB3EXDWBqgD4pCzFS188qVE2QvPtVZlgc_YAP50geCG825LYvffAP1dDRZz0t24PHhx9Qj-UpzbyRsj7NiZHL9mui3kM4mLFNEqFiZimU7zKL2pQCYR_RiXcSGCEJF0oFpN-LS5ns7BqF2rKzQ1MzMyFH9ss2qMeJLfSdsYtjEqoB8jjLp5odq6ys2gYHpibuoPLEtRvQQ',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZanOqSCaNKVYBud2coSJo2-wNR0noBa4C5o7IYKgJcDhW9IgnAv9o2eL3bYbdr28JiB3EXDWBqgD4pCzFS188qVE2QvPtVZlgc_YAP50geCG825LYvffAP1dDRZz0t24PHhx9Qj-UpzbyRsj7NiZHL9mui3kM4mLFNEqFiZimU7zKL2pQCYR_RiXcSGCEJF0oFpN-LS5ns7BqF2rKzQ1MzMyFH9ss2qMeJLfSdsYtjEqoB8jjLp5odq6ys2gYHpibuoPLEtRvQQ',
    title: 'Alps Summit Reflection',
    filename: 'DSC0421_Alps_Summit.jpg',
    date: 'Oct 14, 2023',
    location: 'Bavaria, Germany',
    camera: 'Sony A7R IV',
    dimensions: '6000 x 4000 px',
    description: 'Captured during the golden hour near the Eibsee lake, Germany.',
    notes: "The clarity of the water on this particular morning provided a near-perfect mirror finish. The exposure was adjusted slightly to preserve the highlights in the snow-capped peaks while maintaining the deep blues of the lake bed.",
    tags: ['Landscape', 'Nature', 'Travel'],
    category: 'nature',
    group: 'November',
    alt: 'High resolution mountain lake landscape',
    span: 'wide',
  },
  {
    id: 'img-2',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUT4fKMQZfGA2FRpztLNoD-4pJV4-dMPASmNBa9HfYeTeQm_ZdS28LhUOVF-uVo3xcBcDZB_00afqVms2CWO_a7UVCZvL0YW_9Of-K5jP3pcUiPwp39cwpGxn6a3dFwyppsdLvCuHu7B1phuP0NIf5_VKUrmIxizM-3XZQaa0L4RJX1vgrZQqHXjXS83IIkaI6g5tw4Diy5hgmqzPwuagOGIMw_KpIqY2BgklyZYspNWZVaTO0Ky-5VzfGJdHR1GyF_n6qAZonaw',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUT4fKMQZfGA2FRpztLNoD-4pJV4-dMPASmNBa9HfYeTeQm_ZdS28LhUOVF-uVo3xcBcDZB_00afqVms2CWO_a7UVCZvL0YW_9Of-K5jP3pcUiPwp39cwpGxn6a3dFwyppsdLvCuHu7B1phuP0NIf5_VKUrmIxizM-3XZQaa0L4RJX1vgrZQqHXjXS83IIkaI6g5tw4Diy5hgmqzPwuagOGIMw_KpIqY2BgklyZYspNWZVaTO0Ky-5VzfGJdHR1GyF_n6qAZonaw',
    title: 'Architectural Shadow',
    filename: 'arch_shadow_014.jpg',
    date: 'Aug 14, 2023',
    location: 'San Francisco, CA',
    camera: 'Fuji X-T5',
    dimensions: '4000 x 5000 px',
    description: 'Dramatic architectural shadow on a white minimalist building.',
    notes: 'A study in negative space and light geometry.',
    tags: ['Architecture', 'Minimal'],
    category: 'all',
    group: 'November',
    alt: 'Dramatic architectural shadow on a white minimalist building',
    span: 'tall',
  },
  {
    id: 'img-3',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZtypND-dDf6iOaSrhvAXs_ynHYwxtcV9cXkZmkzQoPEv3fYbUPlugYJTigrk63X_AN5lq1mNPVvBEWZ_fVlGdpy4GR3Iy12n1MeuL94ICAWPmEl6HE2j_zKbnHpCjjimAydT3jfgT7yiR3zF0tJf6hV8Vz7sheCB2V_Yb5ajGX190NPR_5D6DNf1-_yJxNobpdrKY1puku_H5ONgDMk5BwHDI5X4TqXerymuZk2VYf1fwpUefs5t50lVzQH32V0Url3OMWJwzaQ',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZtypND-dDf6iOaSrhvAXs_ynHYwxtcV9cXkZmkzQoPEv3fYbUPlugYJTigrk63X_AN5lq1mNPVvBEWZ_fVlGdpy4GR3Iy12n1MeuL94ICAWPmEl6HE2j_zKbnHpCjjimAydT3jfgT7yiR3zF0tJf6hV8Vz7sheCB2V_Yb5ajGX190NPR_5D6DNf1-_yJxNobpdrKY1puku_H5ONgDMk5BwHDI5X4TqXerymuZk2VYf1fwpUefs5t50lVzQH32V0Url3OMWJwzaQ',
    title: 'Mountain Serenity',
    filename: 'mountain_lake_003.jpg',
    date: 'Nov 02, 2023',
    location: 'Swiss Alps',
    camera: 'Nikon Z9',
    dimensions: '8256 x 5504 px',
    description: 'Crystal clear mountain lake at dawn.',
    notes: 'Part of the "Continental Serenity" series.',
    tags: ['Landscape', 'Nature'],
    category: 'nature',
    group: 'November',
    alt: 'Mountain lake at dawn with reflections',
    span: 'normal',
  },
  {
    id: 'img-4',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5OCwMiR5BHuZm5fvqqUjn_WRlxvMbJ0WjbrnYqXq21zbTUG0ge0VLcWeQdlq3onC3cI1aHgpxjasUpSsLuphtyZkOfiXjT0of5JD8JqGJg8MsJ7M9dF4fnGwufa3sNSE5q1058FZibZuQ5OLQcrv5cjw6kvWAZR5WbOnTWQLajXWRVHL0tS7XwhMHGVDTImtKqXX8ZNFiRl_cOL1iFnC8Ome1aSke9Ij220wFqzyT4ZD9HyBsNecvgZ6s5EdjeunqvnaFlkV_5A',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5OCwMiR5BHuZm5fvqqUjn_WRlxvMbJ0WjbrnYqXq21zbTUG0ge0VLcWeQdlq3onC3cI1aHgpxjasUpSsLuphtyZkOfiXjT0of5JD8JqGJg8MsJ7M9dF4fnGwufa3sNSE5q1058FZibZuQ5OLQcrv5cjw6kvWAZR5WbOnTWQLajXWRVHL0tS7XwhMHGVDTImtKqXX8ZNFiRl_cOL1iFnC8Ome1aSke9Ij220wFqzyT4ZD9HyBsNecvgZ6s5EdjeunqvnaFlkV_5A',
    title: 'Portrait in Soft Light',
    filename: 'portrait_softlight_07.jpg',
    date: 'Sep 18, 2023',
    location: 'Studio',
    camera: 'Canon R5',
    dimensions: '5472 x 3648 px',
    description: 'Soft lit portrait of a woman looking away.',
    notes: 'Natural window light with reflector bounce.',
    tags: ['Portrait', 'People'],
    category: 'people',
    group: 'People',
    alt: 'Soft lit portrait of a woman looking away',
    span: 'normal',
  },
  {
    id: 'img-5',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDB6Q7Fts8rigeXQxYFna8jChP8afx3vZMF0iJ2WGHZkrKSeDZlLI-LHIgzFkgmsSQrDCJPvgCd-GQ2m6epyeXjZEoVsAsBxAgxRQuoqPUkapBQsmie6sr96e2GdpfwdYaYBNiZH6qt1qp1tzqKh2LrPBmB_u_LtBn-ll4SAy6kdS4QDauz75VXwPHbPU6T3VlOBdgJLLdsODgQ1rFxdP7VmEzONh4cqM7qlzQdJAtbMZWJaza3I90uiZ6eqau2XJu1m4o4Y6xclQ',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDB6Q7Fts8rigeXQxYFna8jChP8afx3vZMF0iJ2WGHZkrKSeDZlLI-LHIgzFkgmsSQrDCJPvgCd-GQ2m6epyeXjZEoVsAsBxAgxRQuoqPUkapBQsmie6sr96e2GdpfwdYaYBNiZH6qt1qp1tzqKh2LrPBmB_u_LtBn-ll4SAy6kdS4QDauz75VXwPHbPU6T3VlOBdgJLLdsODgQ1rFxdP7VmEzONh4cqM7qlzQdJAtbMZWJaza3I90uiZ6eqau2XJu1m4o4Y6xclQ',
    title: 'Candid Portrait',
    filename: 'candid_man_natural.jpg',
    date: 'Sep 20, 2023',
    location: 'Brooklyn, NY',
    camera: 'Leica Q3',
    dimensions: '4000 x 5000 px',
    description: 'Candid portrait of a man in natural light.',
    notes: 'Street capture, available light only.',
    tags: ['Portrait', 'Street'],
    category: 'people',
    group: 'People',
    alt: 'Candid portrait of a man in natural light',
    span: 'normal',
  },
  {
    id: 'img-6',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByeoAJ_PWvAEiHkfU_9Ty1-1ZlnjUbDoRrNdm7L3id4VozW-6_amWaEmWG5L1agLOhawTMNeSw72skyUVtudJESJOjOtdC23BF5DJViMYhlJVAQ5ljVN5hbClHwF_Kn2LwJbaaHmtKqSec5SvUDeZ321F7rU2ai724ABPux6aRSECVbMl5OiFcjJ4YTpqgvvKAc0e4M4ylGNfQXCCHIe8dPT6LCbcB-D9bKKmQBOkirdOnIJZA_XwBkCTm5oH9M1_fRsULJgdDbg',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByeoAJ_PWvAEiHkfU_9Ty1-1ZlnjUbDoRrNdm7L3id4VozW-6_amWaEmWG5L1agLOhawTMNeSw72skyUVtudJESJOjOtdC23BF5DJViMYhlJVAQ5ljVN5hbClHwF_Kn2LwJbaaHmtKqSec5SvUDeZ321F7rU2ai724ABPux6aRSECVbMl5OiFcjJ4YTpqgvvKAc0e4M4ylGNfQXCCHIe8dPT6LCbcB-D9bKKmQBOkirdOnIJZA_XwBkCTm5oH9M1_fRsULJgdDbg',
    title: 'Classic Headshot',
    filename: 'headshot_neutral_01.jpg',
    date: 'Oct 01, 2023',
    location: 'Studio',
    camera: 'Canon R5',
    dimensions: '5472 x 3648 px',
    description: 'Classic headshot with neutral expression.',
    notes: '',
    tags: ['Portrait', 'Headshot'],
    category: 'people',
    group: 'People',
    alt: 'Classic headshot of a person with neutral expression',
    span: 'normal',
  },
  {
    id: 'img-7',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYUcLXRX-UyiaydqGXxF1fpdkC4x2bl0sc--TypFVzVCKmYkxyjEeCcSx33LGsz5Hqc_NVfR112ge2ZiBSW0OENMqeE6yjNhfkzuQ5RfTv9Yallrup7vrVfHps7wA0xBEDybl4mR5Z4zvAsErOmEHEDdSX7BPEqN08Zw2Kw3U1r_BwWV_NNiOWBNlVbzFz3Y0j0wchomPzRveaHqJw6YKu23RQ6Mjh3AhygDUMLSdgpM2JApDvI1Me_BOeGhEJvZN5ydD-5SuPHQ',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYUcLXRX-UyiaydqGXxF1fpdkC4x2bl0sc--TypFVzVCKmYkxyjEeCcSx33LGsz5Hqc_NVfR112ge2ZiBSW0OENMqeE6yjNhfkzuQ5RfTv9Yallrup7vrVfHps7wA0xBEDybl4mR5Z4zvAsErOmEHEDdSX7BPEqN08Zw2Kw3U1r_BwWV_NNiOWBNlVbzFz3Y0j0wchomPzRveaHqJw6YKu23RQ6Mjh3AhygDUMLSdgpM2JApDvI1Me_BOeGhEJvZN5ydD-5SuPHQ',
    title: 'Mountain Grandeur',
    filename: 'mountain_peaks_wide.jpg',
    date: 'Oct 10, 2023',
    location: 'Rocky Mountains',
    camera: 'Sony A7R IV',
    dimensions: '7952 x 5304 px',
    description: 'Grand mountain range with snow-capped peaks and clouds.',
    notes: 'Shot at 6am after a 4-hour hike.',
    tags: ['Landscape', 'Mountains', 'Travel'],
    category: 'nature',
    group: 'October',
    alt: 'Grand mountain range with snow-capped peaks and clouds',
    span: 'wide',
  },
  {
    id: 'img-8',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPsiunoripILqGxcCIV1JJgD6NA0muA-bjVkDDQrxAeT5E8AKIjEgZaMmhF43hXIuZeHrPrvqZcxyfOou3MWXD3S_g7N4T8Tp0IQZXryHqizS1e4lECLjwlBifu0mHbdWIM6mePiWFmin3dUUT2AJ10EuM-lC8sLHNkZufZySL5_7E5To-_rXO6IOngLyCw-fR1JNCPewaCSxXYoOhBxSijG-fObkqf_YOLlgH9Lpy3L4Pzm-6vCzMv1T3Nq_gcCuGe7hhRHR8Ig',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPsiunoripILqGxcCIV1JJgD6NA0muA-bjVkDDQrxAeT5E8AKIjEgZaMmhF43hXIuZeHrPrvqZcxyfOou3MWXD3S_g7N4T8Tp0IQZXryHqizS1e4lECLjwlBifu0mHbdWIM6mePiWFmin3dUUT2AJ10EuM-lC8sLHNkZufZySL5_7E5To-_rXO6IOngLyCw-fR1JNCPewaCSxXYoOhBxSijG-fObkqf_YOLlgH9Lpy3L4Pzm-6vCzMv1T3Nq_gcCuGe7hhRHR8Ig',
    title: 'Forest Light',
    filename: 'forest_sunbeams.jpg',
    date: 'Oct 12, 2023',
    location: 'Black Forest, Germany',
    camera: 'Nikon Z6 II',
    dimensions: '6048 x 4024 px',
    description: 'Sunbeams filtering through a dense green forest.',
    notes: '',
    tags: ['Nature', 'Forest'],
    category: 'nature',
    group: 'October',
    alt: 'Sunbeams filtering through a dense green forest',
    span: 'normal',
  },
  {
    id: 'img-9',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8rgxUJzaGbUEHJxDJu2ckC3-QtwXEfRW8L654iLzG0bgfaZVRPSF0Po5SzkjlVKepYfNsYLyv8cREdx7hfNI4JQYhpD7NqHk43Sg2Of3CVZKci5OM4PsUkabLC3AHoJizVaV8gJU3nscaYNtvN3kSKxDc2lgQ-au_Hzy1ICf3wh04fHR7keed6ns2K1HLRQB0nmmXVPFYVLS_cYQFbgmr_znTv1D5eYhdSgPamLJdoNSJ3fhKqlGd3EJ1UUgldd-mmWdXRMT8aQ',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8rgxUJzaGbUEHJxDJu2ckC3-QtwXEfRW8L654iLzG0bgfaZVRPSF0Po5SzkjlVKepYfNsYLyv8cREdx7hfNI4JQYhpD7NqHk43Sg2Of3CVZKci5OM4PsUkabLC3AHoJizVaV8gJU3nscaYNtvN3kSKxDc2lgQ-au_Hzy1ICf3wh04fHR7keed6ns2K1HLRQB0nmmXVPFYVLS_cYQFbgmr_znTv1D5eYhdSgPamLJdoNSJ3fhKqlGd3EJ1UUgldd-mmWdXRMT8aQ',
    title: 'Autumn River',
    filename: 'aerial_river_autumn.jpg',
    date: 'Oct 13, 2023',
    location: 'Vermont, USA',
    camera: 'DJI Mavic 3',
    dimensions: '5280 x 3956 px',
    description: 'Aerial view of a winding river in autumn.',
    notes: 'Drone shot at 200ft altitude.',
    tags: ['Aerial', 'Landscape', 'Autumn'],
    category: 'nature',
    group: 'October',
    alt: 'Aerial view of a winding river in autumn',
    span: 'normal',
  },
  {
    id: 'img-10',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYXD3uWEbc83eoazB3vwh4nPzifLOED5CMYhek1LDmtwl-RYcUPPqFFUWj6YdBgfVbdAXBEMy6iHjGWKbZ-0Fm8mIyZa1SYITW9HvhbjJVbBNweMx296An29e7pgNZq_TaZUNqrMNhSuv0dIjO8r2Rzq-H59F2igUtCgjGEAGVB_at182eZN0twu585nqQy1Nz_rlRZE998cB6eP7g9zQApYrb9uwIJasMgfXBM-96PmqHgBnVMjhHUqb9yEY6DImdI1CuTui7_g',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYXD3uWEbc83eoazB3vwh4nPzifLOED5CMYhek1LDmtwl-RYcUPPqFFUWj6YdBgfVbdAXBEMy6iHjGWKbZ-0Fm8mIyZa1SYITW9HvhbjJVbBNweMx296An29e7pgNZq_TaZUNqrMNhSuv0dIjO8r2Rzq-H59F2igUtCgjGEAGVB_at182eZN0twu585nqQy1Nz_rlRZE998cB6eP7g9zQApYrb9uwIJasMgfXBM-96PmqHgBnVMjhHUqb9yEY6DImdI1CuTui7_g',
    title: 'Meadow Sunset',
    filename: 'meadow_golden_hour.jpg',
    date: 'Oct 14, 2023',
    location: 'Cotswolds, UK',
    camera: 'Canon R6',
    dimensions: '5472 x 3648 px',
    description: 'Beautiful sunset over a peaceful country meadow.',
    notes: '',
    tags: ['Landscape', 'Sunset'],
    category: 'nature',
    group: 'October',
    alt: 'Beautiful sunset over a peaceful country meadow',
    span: 'normal',
  },
  {
    id: 'img-11',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQYS3OIfXqt0afjB7wuQ0Wy7Fe6opyFbg7WzKWkffHbsNb9NrEbcEsIyT6qRnpv6UqOx047z5WrQcCMZFjI2yZ3ySaDd4aqdnRPGikS8tt7D0ouY6gGwJxSO1gnXlCX5kjOxGgXXJQcxcDD2ga-2IYTH_yZGdg_WpxkM-qBnIggnODoQdOvnF6HJbcEbGfW8XNmEH9JAjL6aFH22iLxfyeA4Cc_LZbJkuFSR-biE7h6d6nTIYtzfKP-tYevBmIlUkxlWpsq5ZKfw',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQYS3OIfXqt0afjB7wuQ0Wy7Fe6opyFbg7WzKWkffHbsNb9NrEbcEsIyT6qRnpv6UqOx047z5WrQcCMZFjI2yZ3ySaDd4aqdnRPGikS8tt7D0ouY6gGwJxSO1gnXlCX5kjOxGgXXJQcxcDD2ga-2IYTH_yZGdg_WpxkM-qBnIggnODoQdOvnF6HJbcEbGfW8XNmEH9JAjL6aFH22iLxfyeA4Cc_LZbJkuFSR-biE7h6d6nTIYtzfKP-tYevBmIlUkxlWpsq5ZKfw',
    title: 'Volcanic Waterfall',
    filename: 'waterfall_volcanic.jpg',
    date: 'Oct 16, 2023',
    location: 'Iceland',
    camera: 'Sony A7 IV',
    dimensions: '6000 x 4000 px',
    description: 'Dramatic waterfall cascading down dark volcanic rocks.',
    notes: 'Long exposure at 1/4s, tripod required.',
    tags: ['Waterfall', 'Iceland', 'Nature'],
    category: 'nature',
    group: 'October',
    alt: 'Dramatic waterfall cascading down dark volcanic rocks',
    span: 'normal',
  },
  {
    id: 'img-12',
    src: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=600&q=70',
    videoSrc: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    mediaType: 'video',
    title: 'City Rooftop Reel',
    filename: 'reel_city_rooftop_001.mp4',
    date: 'Nov 08, 2023',
    location: 'New York, USA',
    camera: 'iPhone 15 Pro',
    dimensions: '3840 x 2160 px',
    description: 'Short rooftop video clip during a vibrant blue-hour skyline.',
    notes: 'Captured handheld and stabilized in post for a smooth social reel format.',
    tags: ['Video', 'City', 'Reel'],
    category: 'selfies',
    group: 'November',
    alt: 'Blue-hour city skyline from rooftop captured as a video reel',
    span: 'wide',
  },
  {
    id: 'img-13',
    src: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=70',
    videoSrc: 'https://samplelib.com/lib/preview/mp4/sample-10s.mp4',
    mediaType: 'video',
    title: 'Makeup Timelapse Session',
    filename: 'timelapse_makeup_004.mp4',
    date: 'Sep 26, 2023',
    location: 'Studio',
    camera: 'Sony ZV-E10',
    dimensions: '1920 x 1080 px',
    description: 'Behind-the-scenes portrait prep captured as a short timelapse.',
    notes: 'Natural key light with a soft fill; exported for quick portfolio preview.',
    tags: ['Video', 'People', 'BTS'],
    category: 'people',
    group: 'People',
    alt: 'Studio makeup timelapse of portrait preparation',
    span: 'normal',
  },
  {
    id: 'img-14',
    src: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=1200&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=600&q=70',
    videoSrc: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
    mediaType: 'video',
    title: 'Mirror Selfie Clip',
    filename: 'selfie_mirror_clip_002.mp4',
    date: 'Oct 21, 2023',
    location: 'Los Angeles, CA',
    camera: 'Samsung S23 Ultra',
    dimensions: '1080 x 1920 px',
    description: 'Portrait-oriented selfie video with soft indoor lighting.',
    notes: 'Recorded for quick style references and skin-tone checks under warm light.',
    tags: ['Video', 'Selfie', 'Portrait'],
    category: 'selfies',
    group: 'October',
    alt: 'Portrait selfie video clip in warm indoor light',
    span: 'tall',
  },
];

export const GALLERY_GROUPS = [
  { id: 'november', label: 'November', count: 4 },
  { id: 'people', label: 'People', count: 4 },
  { id: 'october', label: 'October', count: 6 },
];